# Generated by Django 5.2.1 on 2025-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_completed_task_ncompleted_remove_task_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(default='preet', max_length=200)),
                ('n_completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='ncompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ntitle',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
