# Generated by Django 5.2.1 on 2025-05-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_new_n_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='n_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='n_title',
            new_name='title',
        ),
    ]
