# Generated by Django 5.2.1 on 2025-05-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_n_completed_new_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='new',
            old_name='completed',
            new_name='n_completed',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='n_title',
        ),
    ]
