# Generated by Django 5.2.1 on 2025-05-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
